; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30146.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	wWinMain
; Function compile flags: /Odtp
; File C:\Users\90722\source\repos\µ¹Ðð¼ÓÃÜ\test.c
_TEXT	SEGMENT
hInstance$ = 8
hPrevInstance$ = 16
lpCmdLine$ = 24
nCmdShow$ = 32
wWinMain PROC

; 7    : {

	mov	DWORD PTR [rsp+32], r9d
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx

; 8    :     return 1;

	mov	eax, 1

; 9    : }

	ret	0
wWinMain ENDP
_TEXT	ENDS
END
